# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

---
url: "https://christophersiems.github.io/"
repository: "ChristopherSiems/ChristopherSiems.github.io"
locale: "en-US"
date_format: "%Y.%m.%d"
title: &name "Christopher Siems"
title_separator: "|"
description: &bio "Hi! My name is Christopher Siems and I am a computer science, data science, and math student at Clark University; and welcome to my personal website and blog!"
search: true
breadcrumbs: true
show_date: true
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"
markdown: "kramdown"

author:
  name: *name
  avatar: "assets/images/chris_siems-square-500.jpg"
  bio: *bio
  links: 
    - &github
      label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/ChristopherSiems"
    - &linkedin
      label: "LinkedIn"
      icon: "fa-brands fa-linkedin-in"
      url: "https://www.linkedin.com/in/christopher-siems/"
    - &orcid
      label: "ORCID"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/0009-0002-4751-1759"
    - &acm
      label: "ACM"
      icon: "fa-solid fa-code"
      url: "https://dl.acm.org/profile/99661423798"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      show_date: true
      enable_copy_code_button: true
      author_profile: true
      share: true
      related: true
      layout: "single"

footer:
  links:
    - *github
    - *linkedin
    - *orcid
    - *acm

compress_html:
  clippings: "all"

atom_feed:
  hide: true

plugins:
  - "jekyll-feed"
  - "jekyll-include-cache"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
