---
url: "https://christophersiems.github.io/"
repository: "ChristopherSiems/ChristopherSiems.github.io"
locale: "en-US"
date_format: "%Y.%m.%d"
title: &name "Christopher Siems"
title_separator: "|"
description: &bio "Hi! My name is Christopher Siems and I am a computer science, data science, and math student at Clark University; and welcome to my personal website and blog!"
search: true
breadcrumbs: false
show_date: true
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"
markdown: "kramdown"

# Author config
author:
  name: *name
  avatar: "assets/images/chris_siems-square-500.jpg"
  bio: *bio
  links: 
    - &github
      label: "GitHub"
      icon: "fa-brands fa-github"
      url: "https://github.com/ChristopherSiems"
    - &linkedin
      label: "LinkedIn"
      icon: "fa-brands fa-linkedin-in"
      url: "https://www.linkedin.com/in/christopher-siems/"
    - &orcid
      label: "ORCID"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/0009-0002-4751-1759"
    - &acm
      label: "ACM"
      icon: "fa-solid fa-code"
      url: "https://dl.acm.org/profile/99661423798"

# Default post settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      show_date: true
      enable_copy_code_button: true
      author_profile: true
      share: true
      related: true
      layout: "single"

# Footer settings
footer:
  links:
    - *github
    - *linkedin
    - *orcid
    - *acm

# Compress HTML
compress_html:
  clippings: "all"

# Plugins
plugins:
  - "jekyll-include-cache"
  - "jekyll-seo-tag"
  - "jekyll-feed"
